# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bottles', models.BooleanField(default=0)),
                ('keg', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address_1', models.CharField(max_length=128)),
                ('city', models.CharField(default='Seal Rock', max_length=64)),
                ('state', models.CharField(default='OR', max_length=2)),
                ('zip_code', models.CharField(default='97376', max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='vendor',
            field=models.ManyToManyField(to='beerfinder.Vendor'),
        ),
    ]
