# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beerfinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.CharField(max_length=255)),
                ('lon', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='address_1',
            new_name='address',
        ),
        migrations.AddField(
            model_name='vendor',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beerfinder.Marker'),
        ),
    ]
