# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beerfinder', '0002_auto_20160816_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottles', models.BooleanField(default=0)),
                ('keg', models.BooleanField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='beer',
            name='bottles',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='keg',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='vendor',
        ),
        migrations.AddField(
            model_name='type',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerfinder.Beer'),
        ),
        migrations.AddField(
            model_name='type',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerfinder.Vendor'),
        ),
    ]
